In R, the fundamental data type is the vector.

Critical to working with vectors is an understanding of:

- recycling
- filtering
- vectorization



## Vector length is Immutable

In [2]:
x <- c(88,5,12,13)

In [3]:
x <- c(x[1:3], 168, x[4])

In [4]:
x

[1]  88   5  12 168  13

In [5]:
x <- c(x[1:3],x[5])

In [6]:
x

[1] 88  5 12 13

## Matrices are Vectors

In [7]:
cbind(c(1,3),c(2,4))

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [8]:
cbind(c(1,3),c(2,4)) + 10:13

[,1] [,2]
[1,] 11   14  
[2,] 14   17

## Recycling

When applying an operation to two vectors that requires them to be the same length, R automatically **recycles**, or repeats, the shorter one, until it is long enough to match the longer one.

In [9]:
c(1,2,4) + c(6,0,9,20,22)

Warning message in c(1, 2, 4) + c(6, 0, 9, 20, 22):
“longer object length is not a multiple of shorter object length”

[1]  7  2 13 21 24

This is equivalent to 

In [10]:
c(1,2,4,1,2) + c(6,0,9,20,22)

[1]  7  2 13 21 24

This can be very useful for matrices.

In [11]:
m <- cbind(c(1,2,3),c(4,5,6))
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [12]:
m + c(1,2)

[,1] [,2]
[1,] 2    6   
[2,] 4    6   
[3,] 4    8

This is equivalent to 

In [13]:
m + c(1,2,1,2,1,2)

[,1] [,2]
[1,] 2    6   
[2,] 4    6   
[3,] 4    8

Here, $m$, a 3x2 matrix, is also a six-element vector, which in R is stored column by column.

The entire operation amounts to

$$
\left(\begin{matrix}1 & 4 \\ 2 & 5 \\ 3 & 6 \end{matrix}\right) +
\left(\begin{matrix}1 & 2 \\ 2 & 1 \\ 1 & 2 \end{matrix}\right)
$$

# Vector Operations

Scalars are one-element vectors. So adding a scalar to a vector will result in the scalar being recycled to the proper length i.e. these two operations are equivalent

In [14]:
c(1,2,3) + 1

[1] 2 3 4

In [15]:
c(1,2,3) + c(1,1,1)

[1] 2 3 4

Furthermore, vector additions are applied element-wise in all cases

In [16]:
c(1,2,4) + c(5,0,-1)

[1] 6 2 3

### Vector Multiplication is Not What You Might Expect

In [17]:
c(1,2,4) * c(5,0,-1)

[1]  5  0 -4

The multiplication is applied element-wise. 

The dot product is performed using the `%*%` operator.

In [18]:
c(1,2,4) %*% c(5,0,-1)

[,1]
[1,] 1

### Every operator is by default applied element-wise

In [19]:
c(1,2,4) / c(5,4,-1)

[1]  0.2  0.5 -4.0

In [20]:
c(1,2,4) %% c(5,4,-1)

[1] 1 2 0

In [21]:
c(1,2,4) ** c(5,4,-1)

[1]  1.00 16.00  0.25

In [22]:
c(1,2,4) ^ c(5,4,-1)

[1]  1.00 16.00  0.25

In [23]:
c(1,2,4) - c(5,4,-1)

[1] -4 -2  5

## Vector Indexing


Vector indexing is where we form a subvector by picking elements of the given vector for specific indices.

The format is `vector1[vector2]`, with the result that we select those elements of `vector1` whose indices are given in `vector2`.

In [24]:
y <- c(1.2,3.9,0.4,0.12)
y[c(1,3)]

[1] 1.2 0.4

In [25]:
y[2:3]

[1] 3.9 0.4

In [26]:
v <- c(2:4)

In [27]:
y[v]

[1] 3.90 0.40 0.12

In [28]:
y[c(1,1,1,3)]

[1] 1.2 1.2 1.2 0.4

Negative subscripts mean that we want to exclude the given elements in the output.

In [29]:
y[-1:-2]

[1] 0.40 0.12

In [30]:
y[1:(length(y)-1)]

[1] 1.2 3.9 0.4

In [31]:
y[-length(y)]

[1] 1.2 3.9 0.4

## Generating Vectors

####  with the `:` Operator

In [32]:
5:8

[1] 5 6 7 8

In [33]:
5:1

[1] 5 4 3 2 1

Mind your operator precedence.

In [34]:
i <- 10

In [35]:
1:i-1

[1] 0 1 2 3 4 5 6 7 8 9

In [36]:
1:(i-1)

[1] 1 2 3 4 5 6 7 8 9

#### `seq`

In [37]:
seq(12,30,by=3)

[1] 12 15 18 21 24 27 30

In [38]:
seq(1.1,2,length=10)

[1] 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

#### `rep`

In [39]:
rep(8,4)

[1] 8 8 8 8

In [40]:
rep(c(5,12,13),3)

[1]  5 12 13  5 12 13  5 12 13

In [41]:
rep(1:3,2)

[1] 1 2 3 1 2 3

In [42]:
rep(c(5,12,13),each=2)

[1]  5  5 12 12 13 13

## Logical Operators

In [43]:
x <- 1:10

In [44]:
x > 4

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [45]:
any(x > 4)

[1] TRUE

In [46]:
all(x > 4)

[1] FALSE

#### Creating a RELU with a logical operator

A [rectified linear unit](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) or RELU is using commonly in neural networks.

<img src=https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Rectifier_and_softplus_functions.svg/495px-Rectifier_and_softplus_functions.svg.png width=300px>

In [50]:
x <- seq(-5,5,length=20)
x

[1] -5.0000000 -4.4736842 -3.9473684 -3.4210526 -2.8947368 -2.3684211
 [7] -1.8421053 -1.3157895 -0.7894737 -0.2631579  0.2631579  0.7894737
[13]  1.3157895  1.8421053  2.3684211  2.8947368  3.4210526  3.9473684
[19]  4.4736842  5.0000000

In [48]:
x * (x > 0)

[1] 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
 [8] 0.0000000 0.0000000 0.0000000 0.2631579 0.7894737 1.3157895 1.8421053
[15] 2.3684211 2.8947368 3.4210526 3.9473684 4.4736842 5.0000000

In [49]:
library(repr)
options(repr.plot.width=12, repr.plot.height=4)

In [ ]:
plot(x, x * (x > 0))